org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=recruitsmapoverhaul
mod_name=Recruits Map Overhaul
mod_license=MIT
mod_version=0.1.0-beta.1
mod_group_id=me.mss1r.recruitsmapoverhaul
mod_authors=mss1r
mod_description=Map rendering overhaul for the Villager Recruits tactical map.

recruits_modrinth_artifact=villager-recruits
recruits_modrinth_version=1.15.0
recruits_version_range=[1.15.0,)
